<?php

namespace GameBundle\Repository;

/**
 * RecordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordsRepository extends \Doctrine\ORM\EntityRepository
{
}
